-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 02:49:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema headhunter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema headhunter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `headhunter` DEFAULT CHARACTER SET utf8 ;
USE `headhunter` ;

-- -----------------------------------------------------
-- Table `headhunter`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `headhunter`.`admin` (
  `id` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `headhunter`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `headhunter`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  `phone` VARCHAR(45) NULL,
  `logo` BLOB NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `headhunter`.`busymode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `headhunter`.`busymode` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `headhunter`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `headhunter`.`category` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `headhunter`.`vacancy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `headhunter`.`vacancy` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL,
  `desription` VARCHAR(1000) NULL,
  `date` DATE NULL,
  `salary` INT(10) NULL,
  `experiance` VARCHAR(100) NULL,
  `location` VARCHAR(100) NULL,
  `id_busymode` INT(11) NULL,
  `id_company` INT(11) NULL,
  `id_category` INT(11) NULL,
  `id_admin` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `company_idx` (`id_company` ASC),
  INDEX `busymode_idx` (`id_busymode` ASC),
  INDEX `category_idx` (`id_category` ASC),
  INDEX `admin_idx` (`id_admin` ASC),
  CONSTRAINT `company`
    FOREIGN KEY (`id_company`)
    REFERENCES `headhunter`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `busymode`
    FOREIGN KEY (`id_busymode`)
    REFERENCES `headhunter`.`busymode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `category`
    FOREIGN KEY (`id_category`)
    REFERENCES `headhunter`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `admin`
    FOREIGN KEY (`id_admin`)
    REFERENCES `headhunter`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `headhunter` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `headhunter`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
